package com.zxcl.webapp.dto.openapi;

import java.util.Date;

public class ApiCallRecordDTO {
	
	/**
	 * call ID , generated by MySQL, auto increment BIGINT
	 */
	private long callId;
	
	/**
	 * application ID
	 */
	private String appId;
	
	/**
	 * calling method
	 */
	private String method;
	
	/**
	 * call begin time
	 */
	private Date callTm;
	
	/**
	 * S==Success
	 * F==Fail
	 */
	private String resultCode;
	/**
	 * cost time in milliseconds
	 */
	private long costMs;
	
	/**
	 * 网关调用结果消息
	 */
	private String resultMsg;
	/**
	 * 业务返回代码
	 */
	private String bizRetCode;
	/**
	 * 业务返回消息
	 */
	private String bizRetMsg;
	
	public long getCallId() {
		return callId;
	}
	public void setCallId(long callId) {
		this.callId = callId;
	}
	public String getAppId() {
		return appId;
	}
	public void setAppId(String appId) {
		this.appId = appId;
	}
	public String getMethod() {
		return method;
	}
	public void setMethod(String method) {
		this.method = method;
	}
	public Date getCallTm() {
		return callTm;
	}
	public void setCallTm(Date callTm) {
		this.callTm = callTm;
	}
	public String getResultCode() {
		return resultCode;
	}
	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}
	public long getCostMs() {
		return costMs;
	}
	public void setCostMs(long costMs) {
		this.costMs = costMs;
	}
	public String getResultMsg() {
		return resultMsg;
	}
	public void setResultMsg(String resultMsg) {
		this.resultMsg = resultMsg;
	}
	public String getBizRetCode() {
		return bizRetCode;
	}
	public void setBizRetCode(String bizRetCode) {
		this.bizRetCode = bizRetCode;
	}
	public String getBizRetMsg() {
		return bizRetMsg;
	}
	public void setBizRetMsg(String bizRetMsg) {
		this.bizRetMsg = bizRetMsg;
	}
	
}
