package com.zxcl.webapp.dto.openapi;

import java.util.Date;

/**
 * 车牌查询接口调用记录
 * @author wenchang001
 */
public class ApiCallPlateQueryRecordDTO {
	
	/**
	 * call ID , generated by MySQL, auto increment BIGINT
	 */
	private long callId;
	
	/**
	 * application ID
	 */
	private String appId;
	
	/**
	 * calling method
	 */
	private String plateNo;
	
	/**
	 * call begin time
	 */
	private Date crtTm;
	
	/**
	 * 1=查到结果
	 * 0=未查到结果
	 */
	private String queryResult;

	public long getCallId() {
		return callId;
	}

	public void setCallId(long callId) {
		this.callId = callId;
	}

	public String getAppId() {
		return appId;
	}

	public void setAppId(String appId) {
		this.appId = appId;
	}

	public String getPlateNo() {
		return plateNo;
	}

	public void setPlateNo(String plateNo) {
		this.plateNo = plateNo;
	}

	public Date getCrtTm() {
		return crtTm;
	}

	public void setCrtTm(Date crtTm) {
		this.crtTm = crtTm;
	}

	public String getQueryResult() {
		return queryResult;
	}

	public void setQueryResult(String queryResult) {
		this.queryResult = queryResult;
	}
	
}
